spring.application.name=TP-Metodos-Agiles-2026
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false



#--------------------------------SIN DOCKER--------------------------------

# Configuracion para base de datos H2 en memoria (Pruebas locales)
#spring.datasource.url=jdbc:h2:mem:tpmetodosagiles
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# consola de H2 
#spring.h2.console.enabled=true

# generar tablas
#spring.jpa.hibernate.ddl-auto=update