spring.application.name=TP-Metodos-Agiles-2026
spring.datasource.url=jdbc:postgresql://localhost:5432/licencias_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update